FROM node:16

# Create app directory
WORKDIR /web_client

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY ./package*.json ./

# RUN npm ci
RUN npm ci --legacy-peer-deps

# RUN npm audit fix --legacy-peer-deps
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE 4200

CMD ["npm", "run", "start"]